#!/bin/bash
# Parameters:
# config (required)
# autoconf (optional - used by munin-config)

#%# family=manual
#%# capabilities=autoconf

PHP_BIN=${phpbin-"php-fpm"}
PHP_POOLS=${phppool-"www"}
pools=(`echo $PHP_POOLS`)

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo "graph_title PHP5-FPM Processes"
	echo 'graph_args --base 1000 -l 0 '
	echo 'graph_vlabel PHP5-FPM Processes'
	echo 'graph_category PHP'
	echo 'graph_info This graph shows the number of PHP5-FPM processes in the system.'

	for i in `seq 1 ${#pools[@]}`
	do
		pool=${pools[$i-1]}
		echo "$pool.label $pool"
		echo "$pool.draw LINE2"
		echo "$pool.info The current number of $pool"
	done
	exit 0
fi

for i in `seq 1 ${#pools[@]}`
do
	pool=${pools[$i-1]}
	echo -n "$pool.value "
	ps awwwux | grep "$PHP_BIN: pool $pool" | grep -v grep | wc -l
done

